# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PDFdir(object):
    def setupUi(self, PDFdir):
        PDFdir.setObjectName("PDFdir")
        PDFdir.resize(649, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PDFdir.sizePolicy().hasHeightForWidth())
        PDFdir.setSizePolicy(sizePolicy)
        PDFdir.setMinimumSize(QtCore.QSize(330, 450))
        PDFdir.setMaximumSize(QtCore.QSize(1000000, 450))
        PDFdir.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(PDFdir)
        self.centralwidget.setObjectName("centralwidget")
        self.pdf_path_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_path_edit.setGeometry(QtCore.QRect(9, 30, 217, 20))
        self.pdf_path_edit.setObjectName("pdf_path_edit")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(240, 30, 70, 20))
        self.open_button.setObjectName("open_button")
        self.dir_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.dir_text_edit.setGeometry(QtCore.QRect(9, 87, 217, 311))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dir_text_edit.setFont(font)
        self.dir_text_edit.setAcceptRichText(False)
        self.dir_text_edit.setObjectName("dir_text_edit")
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(240, 378, 70, 20))
        self.export_button.setObjectName("export_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 6, 214, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 63, 217, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 65, 54, 13))
        self.label_3.setObjectName("label_3")
        self.offset_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.offset_edit.setGeometry(QtCore.QRect(240, 87, 75, 20))
        self.offset_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.offset_edit.setMaxLength(3)
        self.offset_edit.setObjectName("offset_edit")
        self.level0_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level0_edit.setGeometry(QtCore.QRect(240, 170, 79, 20))
        self.level0_edit.setText("")
        self.level0_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.level0_edit.setObjectName("level0_edit")
        self.level0_box = QtWidgets.QCheckBox(self.centralwidget)
        self.level0_box.setGeometry(QtCore.QRect(240, 150, 49, 16))
        self.level0_box.setObjectName("level0_box")
        self.level1_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level1_edit.setGeometry(QtCore.QRect(240, 220, 79, 20))
        self.level1_edit.setText("")
        self.level1_edit.setObjectName("level1_edit")
        self.level1_box = QtWidgets.QCheckBox(self.centralwidget)
        self.level1_box.setGeometry(QtCore.QRect(240, 200, 49, 16))
        self.level1_box.setObjectName("level1_box")
        self.level2_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level2_edit.setGeometry(QtCore.QRect(240, 270, 79, 20))
        self.level2_edit.setText("")
        self.level2_edit.setObjectName("level2_edit")
        self.level2_box = QtWidgets.QCheckBox(self.centralwidget)
        self.level2_box.setGeometry(QtCore.QRect(240, 250, 49, 16))
        self.level2_box.setObjectName("level2_box")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 300, 54, 12))
        self.label_4.setObjectName("label_4")
        self.select_level_box = QtWidgets.QComboBox(self.centralwidget)
        self.select_level_box.setGeometry(QtCore.QRect(238, 320, 83, 22))
        self.select_level_box.setObjectName("select_level_box")
        self.select_level_box.addItem("")
        self.select_level_box.addItem("")
        self.select_level_box.addItem("")
        self.adv_group = QtWidgets.QGroupBox(self.centralwidget)
        self.adv_group.setEnabled(True)
        self.adv_group.setGeometry(QtCore.QRect(234, 123, 89, 229))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.adv_group.setFont(font)
        self.adv_group.setAutoFillBackground(True)
        self.adv_group.setAlignment(QtCore.Qt.AlignCenter)
        self.adv_group.setFlat(False)
        self.adv_group.setCheckable(False)
        self.adv_group.setObjectName("adv_group")
        self.level0_button = QtWidgets.QPushButton(self.adv_group)
        self.level0_button.setGeometry(QtCore.QRect(66, 24, 19, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.level0_button.setFont(font)
        self.level0_button.setStyleSheet("color: rgb(0, 0, 255)")
        self.level0_button.setFlat(True)
        self.level0_button.setObjectName("level0_button")
        self.pushButton_3 = QtWidgets.QPushButton(self.adv_group)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 88, 19, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 255)")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.level1_button = QtWidgets.QPushButton(self.adv_group)
        self.level1_button.setGeometry(QtCore.QRect(66, 76, 19, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.level1_button.setFont(font)
        self.level1_button.setStyleSheet("color: rgb(0, 0, 255)")
        self.level1_button.setFlat(True)
        self.level1_button.setObjectName("level1_button")
        self.level2_button = QtWidgets.QPushButton(self.adv_group)
        self.level2_button.setGeometry(QtCore.QRect(66, 126, 19, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.level2_button.setFont(font)
        self.level2_button.setStyleSheet("color: rgb(0, 0, 255)")
        self.level2_button.setFlat(True)
        self.level2_button.setObjectName("level2_button")
        self.dir_tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        self.dir_tree_widget.setGeometry(QtCore.QRect(340, 66, 271, 335))
        self.dir_tree_widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.dir_tree_widget.setAcceptDrops(True)
        self.dir_tree_widget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.dir_tree_widget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.dir_tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dir_tree_widget.setObjectName("dir_tree_widget")
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.dir_tree_widget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.dir_tree_widget.headerItem().setFont(1, font)
        self.add_pagenum_box = QtWidgets.QSpinBox(self.centralwidget)
        self.add_pagenum_box.setGeometry(QtCore.QRect(400, 28, 46, 21))
        self.add_pagenum_box.setObjectName("add_pagenum_box")
        self.add_pagenum_to_selected_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_pagenum_to_selected_button.setGeometry(QtCore.QRect(460, 28, 45, 20))
        self.add_pagenum_to_selected_button.setObjectName("add_pagenum_to_selected_button")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 34, 54, 12))
        self.label_5.setObjectName("label_5")
        self.add_pagenum_to_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_pagenum_to_all_button.setGeometry(QtCore.QRect(514, 28, 41, 20))
        self.add_pagenum_to_all_button.setObjectName("add_pagenum_to_all_button")
        self.adv_group.raise_()
        self.pdf_path_edit.raise_()
        self.open_button.raise_()
        self.dir_text_edit.raise_()
        self.export_button.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.offset_edit.raise_()
        self.level0_edit.raise_()
        self.level0_box.raise_()
        self.level1_edit.raise_()
        self.level1_box.raise_()
        self.level2_edit.raise_()
        self.level2_box.raise_()
        self.label_4.raise_()
        self.select_level_box.raise_()
        self.dir_tree_widget.raise_()
        self.add_pagenum_box.raise_()
        self.add_pagenum_to_selected_button.raise_()
        self.label_5.raise_()
        self.add_pagenum_to_all_button.raise_()
        PDFdir.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PDFdir)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        PDFdir.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(PDFdir)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 649, 21))
        self.menuBar.setObjectName("menuBar")
        self.help_menu = QtWidgets.QMenu(self.menuBar)
        self.help_menu.setObjectName("help_menu")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        PDFdir.setMenuBar(self.menuBar)
        self.home_page_action = QtWidgets.QAction(PDFdir)
        self.home_page_action.setObjectName("home_page_action")
        self.help_action = QtWidgets.QAction(PDFdir)
        self.help_action.setObjectName("help_action")
        self.update_action = QtWidgets.QAction(PDFdir)
        self.update_action.setObjectName("update_action")
        self.english_action = QtWidgets.QAction(PDFdir)
        self.english_action.setObjectName("english_action")
        self.chinese_action = QtWidgets.QAction(PDFdir)
        self.chinese_action.setObjectName("chinese_action")
        self.help_menu.addAction(self.home_page_action)
        self.help_menu.addAction(self.help_action)
        self.help_menu.addAction(self.update_action)
        self.menu.addAction(self.english_action)
        self.menu.addAction(self.chinese_action)
        self.menuBar.addAction(self.help_menu.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(PDFdir)
        QtCore.QMetaObject.connectSlotsByName(PDFdir)

    def retranslateUi(self, PDFdir):
        _translate = QtCore.QCoreApplication.translate
        PDFdir.setWindowTitle(_translate("PDFdir", "PDFdir"))
        self.open_button.setText(_translate("PDFdir", "选择文件"))
        self.dir_text_edit.setHtml(_translate("PDFdir", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.export_button.setText(_translate("PDFdir", "写入"))
        self.label.setText(_translate("PDFdir", "PDF文件路径"))
        self.label_2.setText(_translate("PDFdir", "目录文本"))
        self.label_3.setText(_translate("PDFdir", "偏移页"))
        self.offset_edit.setText(_translate("PDFdir", "0"))
        self.level0_box.setText(_translate("PDFdir", "首层"))
        self.level1_box.setText(_translate("PDFdir", "二层"))
        self.level2_box.setText(_translate("PDFdir", "三层"))
        self.label_4.setText(_translate("PDFdir", "未识别"))
        self.select_level_box.setCurrentText(_translate("PDFdir", "首层"))
        self.select_level_box.setItemText(0, _translate("PDFdir", "首层"))
        self.select_level_box.setItemText(1, _translate("PDFdir", "二层"))
        self.select_level_box.setItemText(2, _translate("PDFdir", "三层"))
        self.adv_group.setTitle(_translate("PDFdir", "子目录"))
        self.level0_button.setText(_translate("PDFdir", "..."))
        self.pushButton_3.setText(_translate("PDFdir", "..."))
        self.level1_button.setText(_translate("PDFdir", "..."))
        self.level2_button.setText(_translate("PDFdir", "..."))
        self.dir_tree_widget.headerItem().setText(0, _translate("PDFdir", "目录"))
        self.dir_tree_widget.headerItem().setText(1, _translate("PDFdir", "页数"))
        self.add_pagenum_to_selected_button.setText(_translate("PDFdir", "选中"))
        self.label_5.setText(_translate("PDFdir", "页数增加"))
        self.add_pagenum_to_all_button.setText(_translate("PDFdir", "全部"))
        self.help_menu.setTitle(_translate("PDFdir", "帮助"))
        self.menu.setTitle(_translate("PDFdir", "语言"))
        self.home_page_action.setText(_translate("PDFdir", "主页"))
        self.help_action.setText(_translate("PDFdir", "帮助手册"))
        self.update_action.setText(_translate("PDFdir", "检查更新"))
        self.english_action.setText(_translate("PDFdir", "English"))
        self.chinese_action.setText(_translate("PDFdir", "中文"))

