# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/main.ui'
#
# Created: Thu Aug 10 15:03:59 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(315, 386)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setMinimumSize(QtCore.QSize(315, 386))
		MainWindow.setMaximumSize(QtCore.QSize(315, 386))
		self.centralwidget = QtGui.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.pdf_path_edit = QtGui.QLineEdit(self.centralwidget)
		self.pdf_path_edit.setGeometry(QtCore.QRect(9, 30, 217, 20))
		self.pdf_path_edit.setObjectName("pdf_path_edit")
		self.open_button = QtGui.QPushButton(self.centralwidget)
		self.open_button.setGeometry(QtCore.QRect(237, 30, 70, 20))
		self.open_button.setObjectName("open_button")
		self.dir_text_edit = QtGui.QTextEdit(self.centralwidget)
		self.dir_text_edit.setGeometry(QtCore.QRect(9, 87, 217, 244))
		self.dir_text_edit.setAcceptRichText(False)
		self.dir_text_edit.setObjectName("dir_text_edit")
		self.export_button = QtGui.QPushButton(self.centralwidget)
		self.export_button.setGeometry(QtCore.QRect(237, 312, 70, 20))
		self.export_button.setObjectName("export_button")
		self.label = QtGui.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(9, 9, 73, 16))
		self.label.setObjectName("label")
		self.label_2 = QtGui.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(9, 66, 54, 12))
		self.label_2.setObjectName("label_2")
		self.label_3 = QtGui.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(237, 66, 54, 12))
		self.label_3.setObjectName("label_3")
		self.offset_edit = QtGui.QLineEdit(self.centralwidget)
		self.offset_edit.setGeometry(QtCore.QRect(237, 87, 70, 20))
		self.offset_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
		self.offset_edit.setMaxLength(3)
		self.offset_edit.setObjectName("offset_edit")
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtGui.QStatusBar(MainWindow)
		font = QtGui.QFont()
		font.setPointSize(7)
		self.statusbar.setFont(font)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.menuBar = QtGui.QMenuBar(MainWindow)
		self.menuBar.setGeometry(QtCore.QRect(0, 0, 315, 23))
		self.menuBar.setObjectName("menuBar")
		self.help_menu = QtGui.QMenu(self.menuBar)
		self.help_menu.setObjectName("help_menu")
		MainWindow.setMenuBar(self.menuBar)
		self.home_page_action = QtGui.QAction(MainWindow)
		self.home_page_action.setObjectName("home_page_action")
		self.help_action = QtGui.QAction(MainWindow)
		self.help_action.setObjectName("help_action")
		self.update_action = QtGui.QAction(MainWindow)
		self.update_action.setObjectName("update_action")
		self.help_menu.addAction(self.home_page_action)
		self.help_menu.addAction(self.help_action)
		self.help_menu.addAction(self.update_action)
		self.menuBar.addAction(self.help_menu.menuAction())

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
		self.open_button.setText(QtGui.QApplication.translate("MainWindow", "打开", None, QtGui.QApplication.UnicodeUTF8))
		self.export_button.setText(QtGui.QApplication.translate("MainWindow", "写入目录", None, QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("MainWindow", "PDF文件路径", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("MainWindow", "目录文本", None, QtGui.QApplication.UnicodeUTF8))
		self.label_3.setText(QtGui.QApplication.translate("MainWindow", "偏移页", None, QtGui.QApplication.UnicodeUTF8))
		self.offset_edit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.help_menu.setTitle(QtGui.QApplication.translate("MainWindow", "帮助", None, QtGui.QApplication.UnicodeUTF8))
		self.home_page_action.setText(QtGui.QApplication.translate("MainWindow", "主页", None, QtGui.QApplication.UnicodeUTF8))
		self.help_action.setText(QtGui.QApplication.translate("MainWindow", "帮助手册", None, QtGui.QApplication.UnicodeUTF8))
		self.update_action.setText(QtGui.QApplication.translate("MainWindow", "检查更新", None, QtGui.QApplication.UnicodeUTF8))

