# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PDFdir(object):
    def setupUi(self, PDFdir):
        PDFdir.setObjectName("PDFdir")
        PDFdir.resize(315, 386)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PDFdir.sizePolicy().hasHeightForWidth())
        PDFdir.setSizePolicy(sizePolicy)
        PDFdir.setMinimumSize(QtCore.QSize(315, 386))
        PDFdir.setMaximumSize(QtCore.QSize(315, 386))
        self.centralwidget = QtWidgets.QWidget(PDFdir)
        self.centralwidget.setObjectName("centralwidget")
        self.pdf_path_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_path_edit.setGeometry(QtCore.QRect(9, 30, 217, 20))
        self.pdf_path_edit.setObjectName("pdf_path_edit")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(237, 30, 70, 20))
        self.open_button.setObjectName("open_button")
        self.dir_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.dir_text_edit.setGeometry(QtCore.QRect(9, 87, 217, 244))
        self.dir_text_edit.setAcceptRichText(False)
        self.dir_text_edit.setObjectName("dir_text_edit")
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(237, 312, 70, 20))
        self.export_button.setObjectName("export_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 73, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 66, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(237, 66, 54, 12))
        self.label_3.setObjectName("label_3")
        self.offset_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.offset_edit.setGeometry(QtCore.QRect(237, 87, 70, 20))
        self.offset_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.offset_edit.setMaxLength(3)
        self.offset_edit.setObjectName("offset_edit")
        PDFdir.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PDFdir)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        PDFdir.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(PDFdir)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 315, 23))
        self.menuBar.setObjectName("menuBar")
        self.help_menu = QtWidgets.QMenu(self.menuBar)
        self.help_menu.setObjectName("help_menu")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        PDFdir.setMenuBar(self.menuBar)
        self.home_page_action = QtWidgets.QAction(PDFdir)
        self.home_page_action.setObjectName("home_page_action")
        self.help_action = QtWidgets.QAction(PDFdir)
        self.help_action.setObjectName("help_action")
        self.update_action = QtWidgets.QAction(PDFdir)
        self.update_action.setObjectName("update_action")
        self.english_action = QtWidgets.QAction(PDFdir)
        self.english_action.setObjectName("english_action")
        self.chinese_action = QtWidgets.QAction(PDFdir)
        self.chinese_action.setObjectName("chinese_action")
        self.help_menu.addAction(self.home_page_action)
        self.help_menu.addAction(self.help_action)
        self.help_menu.addAction(self.update_action)
        self.menu.addAction(self.english_action)
        self.menu.addAction(self.chinese_action)
        self.menuBar.addAction(self.help_menu.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(PDFdir)
        QtCore.QMetaObject.connectSlotsByName(PDFdir)

    def retranslateUi(self, PDFdir):
        _translate = QtCore.QCoreApplication.translate
        PDFdir.setWindowTitle(_translate("PDFdir", "PDFdir"))
        self.open_button.setText(_translate("PDFdir", "打开"))
        self.export_button.setText(_translate("PDFdir", "写入导航"))
        self.label.setText(_translate("PDFdir", "PDF文件路径"))
        self.label_2.setText(_translate("PDFdir", "目录文本"))
        self.label_3.setText(_translate("PDFdir", "偏移页"))
        self.offset_edit.setText(_translate("PDFdir", "0"))
        self.help_menu.setTitle(_translate("PDFdir", "帮助"))
        self.menu.setTitle(_translate("PDFdir", "语言"))
        self.home_page_action.setText(_translate("PDFdir", "主页"))
        self.help_action.setText(_translate("PDFdir", "帮助手册"))
        self.update_action.setText(_translate("PDFdir", "检查更新"))
        self.english_action.setText(_translate("PDFdir", "English"))
        self.chinese_action.setText(_translate("PDFdir", "中文"))

