# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PDFdir(object):
    def setupUi(self, PDFdir):
        PDFdir.setObjectName("PDFdir")
        PDFdir.resize(320, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PDFdir.sizePolicy().hasHeightForWidth())
        PDFdir.setSizePolicy(sizePolicy)
        PDFdir.setMinimumSize(QtCore.QSize(315, 386))
        PDFdir.setMaximumSize(QtCore.QSize(320, 500))
        self.centralwidget = QtWidgets.QWidget(PDFdir)
        self.centralwidget.setObjectName("centralwidget")
        self.pdf_path_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_path_edit.setGeometry(QtCore.QRect(9, 30, 217, 20))
        self.pdf_path_edit.setObjectName("pdf_path_edit")
        self.open_button = QtWidgets.QPushButton(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(240, 30, 70, 20))
        self.open_button.setObjectName("open_button")
        self.dir_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.dir_text_edit.setGeometry(QtCore.QRect(9, 87, 217, 311))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dir_text_edit.setFont(font)
        self.dir_text_edit.setAcceptRichText(False)
        self.dir_text_edit.setObjectName("dir_text_edit")
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(240, 380, 70, 20))
        self.export_button.setObjectName("export_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 6, 214, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 63, 217, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 65, 54, 13))
        self.label_3.setObjectName("label_3")
        self.offset_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.offset_edit.setGeometry(QtCore.QRect(240, 87, 70, 20))
        self.offset_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.offset_edit.setMaxLength(3)
        self.offset_edit.setObjectName("offset_edit")
        self.level0_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level0_edit.setGeometry(QtCore.QRect(240, 170, 70, 20))
        self.level0_edit.setText("")
        self.level0_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.level0_edit.setObjectName("level0_edit")
        self.level0_box = QtWidgets.QCheckBox(self.centralwidget)
        self.level0_box.setGeometry(QtCore.QRect(240, 150, 71, 16))
        self.level0_box.setObjectName("level0_box")
        self.level1_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level1_edit.setGeometry(QtCore.QRect(240, 220, 70, 20))
        self.level1_edit.setText("")
        self.level1_edit.setObjectName("level1_edit")
        self.level1_box = QtWidgets.QCheckBox(self.centralwidget)
        self.level1_box.setGeometry(QtCore.QRect(240, 200, 71, 16))
        self.level1_box.setObjectName("level1_box")
        self.level2_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.level2_edit.setGeometry(QtCore.QRect(240, 270, 70, 20))
        self.level2_edit.setText("")
        self.level2_edit.setObjectName("level2_edit")
        self.level2_box = QtWidgets.QCheckBox(self.centralwidget)
        self.level2_box.setGeometry(QtCore.QRect(240, 250, 71, 16))
        self.level2_box.setObjectName("level2_box")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 300, 54, 12))
        self.label_4.setObjectName("label_4")
        self.select_level_box = QtWidgets.QComboBox(self.centralwidget)
        self.select_level_box.setGeometry(QtCore.QRect(240, 320, 69, 22))
        self.select_level_box.setObjectName("select_level_box")
        self.select_level_box.addItem("")
        self.select_level_box.addItem("")
        self.select_level_box.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(234, 123, 82, 229))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.groupBox.raise_()
        self.pdf_path_edit.raise_()
        self.open_button.raise_()
        self.dir_text_edit.raise_()
        self.export_button.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.offset_edit.raise_()
        self.level0_edit.raise_()
        self.level0_box.raise_()
        self.level1_edit.raise_()
        self.level1_box.raise_()
        self.level2_edit.raise_()
        self.level2_box.raise_()
        self.label_4.raise_()
        self.select_level_box.raise_()
        PDFdir.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PDFdir)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        PDFdir.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(PDFdir)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 320, 23))
        self.menuBar.setObjectName("menuBar")
        self.help_menu = QtWidgets.QMenu(self.menuBar)
        self.help_menu.setObjectName("help_menu")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        PDFdir.setMenuBar(self.menuBar)
        self.home_page_action = QtWidgets.QAction(PDFdir)
        self.home_page_action.setObjectName("home_page_action")
        self.help_action = QtWidgets.QAction(PDFdir)
        self.help_action.setObjectName("help_action")
        self.update_action = QtWidgets.QAction(PDFdir)
        self.update_action.setObjectName("update_action")
        self.english_action = QtWidgets.QAction(PDFdir)
        self.english_action.setObjectName("english_action")
        self.chinese_action = QtWidgets.QAction(PDFdir)
        self.chinese_action.setObjectName("chinese_action")
        self.help_menu.addAction(self.home_page_action)
        self.help_menu.addAction(self.help_action)
        self.help_menu.addAction(self.update_action)
        self.menu.addAction(self.english_action)
        self.menu.addAction(self.chinese_action)
        self.menuBar.addAction(self.help_menu.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(PDFdir)
        QtCore.QMetaObject.connectSlotsByName(PDFdir)

    def retranslateUi(self, PDFdir):
        _translate = QtCore.QCoreApplication.translate
        PDFdir.setWindowTitle(_translate("PDFdir", "PDFdir"))
        self.open_button.setText(_translate("PDFdir", "打开"))
        self.dir_text_edit.setHtml(_translate("PDFdir", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.export_button.setText(_translate("PDFdir", "写入导航"))
        self.label.setText(_translate("PDFdir", "PDF文件路径"))
        self.label_2.setText(_translate("PDFdir", "目录文本"))
        self.label_3.setText(_translate("PDFdir", "偏移页"))
        self.offset_edit.setText(_translate("PDFdir", "0"))
        self.level0_box.setText(_translate("PDFdir", "首层"))
        self.level1_box.setText(_translate("PDFdir", "二层"))
        self.level2_box.setText(_translate("PDFdir", "三层"))
        self.label_4.setText(_translate("PDFdir", "未识别"))
        self.select_level_box.setProperty("currentText", _translate("PDFdir", "首层"))
        self.select_level_box.setItemText(0, _translate("PDFdir", "首层"))
        self.select_level_box.setItemText(1, _translate("PDFdir", "二层"))
        self.select_level_box.setItemText(2, _translate("PDFdir", "三层"))
        self.groupBox.setTitle(_translate("PDFdir", "子目录"))
        self.help_menu.setTitle(_translate("PDFdir", "帮助"))
        self.menu.setTitle(_translate("PDFdir", "语言"))
        self.home_page_action.setText(_translate("PDFdir", "主页"))
        self.help_action.setText(_translate("PDFdir", "帮助手册"))
        self.update_action.setText(_translate("PDFdir", "检查更新"))
        self.english_action.setText(_translate("PDFdir", "English"))
        self.chinese_action.setText(_translate("PDFdir", "中文"))

